// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3fh-KQxnJj6bIXJtnWahWgpuz5H2J6FY',
    appId: '1:477533106982:web:1392a7a8e863d54512c7e7',
    messagingSenderId: '477533106982',
    projectId: 'mindspark-d0445',
    authDomain: 'mindspark-d0445.firebaseapp.com',
    storageBucket: 'mindspark-d0445.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_OVLLK42obTiEThpkC0CyLgJlhl9Y3M',
    appId: '1:477533106982:android:dde89e99a330d99e12c7e7',
    messagingSenderId: '477533106982',
    projectId: 'mindspark-d0445',
    storageBucket: 'mindspark-d0445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUYESjJinh4RmP-pqcCwEiwoccVdstKA8',
    appId: '1:477533106982:ios:cd09de5b7f54d5f512c7e7',
    messagingSenderId: '477533106982',
    projectId: 'mindspark-d0445',
    storageBucket: 'mindspark-d0445.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUYESjJinh4RmP-pqcCwEiwoccVdstKA8',
    appId: '1:477533106982:ios:cd09de5b7f54d5f512c7e7',
    messagingSenderId: '477533106982',
    projectId: 'mindspark-d0445',
    storageBucket: 'mindspark-d0445.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3fh-KQxnJj6bIXJtnWahWgpuz5H2J6FY',
    appId: '1:477533106982:web:6c211a6a6d0f0a6b12c7e7',
    messagingSenderId: '477533106982',
    projectId: 'mindspark-d0445',
    authDomain: 'mindspark-d0445.firebaseapp.com',
    storageBucket: 'mindspark-d0445.firebasestorage.app',
  );
}
